# Generated by Django 3.2.5 on 2021-07-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('img', models.ImageField(null=True, upload_to='productimages')),
                ('descrition', models.TextField(max_length=2500)),
            ],
        ),
    ]
